### ISSUE TITLE
Quick Start Videos for xCAT documentation or xcat.org 

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat.org#107]
* [ ] Record Quick start Video
* [ ] write “quick start” steps
* [ ] Record xCAT introduction Video

**Comment by whowutwut** [comment]
@bybai I don't believe this is a 1 day effort, if we want to create a good valuable video, this will take some time.   I will talk to Mark about this and we will start to prepare a script ...  

I may adjust this to be an epic, because we need to scope some things down a bit to make sure the videos we create are valuable.

But i don't think this should block the website from going live.
