### ISSUE TITLE
xCAT 2.13.5 release checklist 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat.org#63]
#Opening this issue to track the required things that need to be done in preparation for the xCAT 2.13.5 release. 

## Preparation

- [x]  Update the xCAT release notes [****]
   https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.5_Release_Notes

- [x]  Modify the xCAT release page in RTD   http://xcat-docs.readthedocs.io/en/2.13.5/overview/xcat2_release.html [****]

- [x]  Update the xcat.org pages, Pull Request:
     - [x] index.html
     - [x] download.html

## Day of Release [****]
- [x]  Update the xcat-core Wiki page and include the sidebar link to the release notes []
        https://github.com/xcat2/xcat-core/wiki
- [x]  Create a release and tag for the 2.13.5 in GitHub  []
        https://github.com/xcat2/xcat-core/releases
- [x]  Update the xcat.org pages
    - [x]  merge master -> stable , then `git pull` on xcat.org server []()
    - [x]  Once the RC build has been blessed, run the promote_build script on xcat.org for 2.13.5[]
    - [x]  Manually symlink for xcat-deps
- [x]  Activate the RTD build for the 2.13.5 release [Done]
  Updated the badge in https://github.com/xcat2/xcat-core/blob/master/README.rst
- [x]  bump up the xCAT Version in the master branch to 2.13.6 [Done]

**Comment by daniceexi** [comment]
@tingtli  Could you use the task list format to list all the items we need to finish in this release cycle? 
- [ ] item 1
- [ ] item 2
