### ISSUE TITLE
xCAT 2.13.6 release checklist 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat.org#69]
Opening this issue to track the required things that need to be done in preparation for the xCAT 2.13.6 release. 

## Preparation

* [ ]  Update the xCAT release notes
   https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.6_Release_Notes

* [ ]  Modify the xCAT release page in RTD   http://xcat-docs.readthedocs.io/en/2.13.6/overview/xcat2_release.html 

*  [ ]  Update the xcat.org pages, Pull Request:
     * [ ] index.html
     * [ ] download.html

## Day of Release 
* [ ]  Update the xcat-core Wiki page and include the sidebar link to the release notes 
        https://github.com/xcat2/xcat-core/wiki
* [ ] Create a release and tag for the 2.13.6 in GitHub  
        https://github.com/xcat2/xcat-core/releases
* [ ]   Update the xcat.org pages
    * [ ]   merge master -> stable , then `git pull` on xcat.org server 
    * [ ]   Once the RC build has been blessed, run the promote_build script on xcat.org for 2.13.6
    * [ ]   Manually symlink for xcat-deps
* [ ]   Activate the RTD build for the 2.13.6 release 
  Updated the badge in https://github.com/xcat2/xcat-core/blob/master/README.rst
* [ ]  bump up the xCAT Version in the master branch to 2.13.6 [Done]

**Comment by daniceexi** [comment]
why did you close this issue?
